# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'About.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_About(object):
    def setupUi(self, About):
        About.setObjectName("About")
        About.resize(415, 219)
        self.label = QtWidgets.QLabel(About)
        self.label.setGeometry(QtCore.QRect(80, 40, 271, 131))
        self.label.setObjectName("label")

        self.retranslateUi(About)
        QtCore.QMetaObject.connectSlotsByName(About)

    def retranslateUi(self, About):
        _translate = QtCore.QCoreApplication.translate
        About.setWindowTitle(_translate("About", "About"))
        self.label.setText(_translate("About", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">欢迎您使用PaddleXserving </span></p><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">如有疑问请联系GitHub</span></p><p align=\"center\"><a href=\"https://github.com/Reatris/PaddleStudio\"><span style=\" font-size:14pt; font-weight:600; text-decoration: underline; color:#0000ff;\">Reatris</span></a></p></body></html>"))
